export const languageNames = new Map<string, string>([
	["am", "Amharic"],
	["az", "Azerbaijani"],
	["ba", "Bashkir"],
	["ber", "Berber"],
	["bg", "Bulgarian"],
	["bn", "Bengali"],
	["bs", "Bosnian"],
	["cs", "Czech"],
	["de", "German"],
	["dv", "Dhivehi (Maldivian)"],
	["en", "English"],
	["es", "Spanish"],
	["fa", "Persian (Farsi)"],
	["fr", "French"],
	["ha", "Hausa"],
	["hi", "Hindi"],
	["id", "Indonesian"],
	["it", "Italian"],
	["ja", "Japanese"],
	["ko", "Korean"],
	["ku", "Kurdish"],
	["ml", "Malayalam"],
	["ms", "Malay"],
	["my", "Burmese"],
	["nl", "Dutch"],
	["no", "Norwegian"],
	["pl", "Polish"],
	["ps", "Pashto"],
	["pt", "Portuguese"],
	["ro", "Romanian"],
	["ru", "Russian"],
	["sd", "Sindhi"],
	["si", "Sinhala"],
	["so", "Somali"],
	["sq", "Albanian"],
	["sv", "Swedish"],
	["sw", "Swahili"],
	["ta", "Tamil"],
	["tg", "Tajik"],
	["th", "Thai"],
	["tr", "Turkish"],
	["tt", "Tatar"],
	["ug", "Uyghur"],
	["ur", "Urdu"],
	["uz", "Uzbek"],
	["zh", "Chinese"],
]);
